// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/GophKeeper/internal/client/dto"
	grpc "github.com/GophKeeper/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockClient) AuthUser(ctx context.Context, request *grpc.AuthUserRequest) (*grpc.AuthUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", ctx, request)
	ret0, _ := ret[0].(*grpc.AuthUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockClientMockRecorder) AuthUser(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockClient)(nil).AuthUser), ctx, request)
}

// SavePrivateData mocks base method.
func (m *MockClient) SavePrivateData(ctx context.Context, request *dto.SavePrivateDataRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateData", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateData indicates an expected call of SavePrivateData.
func (mr *MockClientMockRecorder) SavePrivateData(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateData", reflect.TypeOf((*MockClient)(nil).SavePrivateData), ctx, request)
}
