// Code generated by MockGen. DO NOT EDIT.
// Source: internal/kafka/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKafkaService is a mock of KafkaService interface.
type MockKafkaService struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaServiceMockRecorder
}

// MockKafkaServiceMockRecorder is the mock recorder for MockKafkaService.
type MockKafkaServiceMockRecorder struct {
	mock *MockKafkaService
}

// NewMockKafkaService creates a new mock instance.
func NewMockKafkaService(ctrl *gomock.Controller) *MockKafkaService {
	mock := &MockKafkaService{ctrl: ctrl}
	mock.recorder = &MockKafkaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaService) EXPECT() *MockKafkaServiceMockRecorder {
	return m.recorder
}

// ReadMessage mocks base method.
func (m *MockKafkaService) ReadMessage(ctx context.Context, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockKafkaServiceMockRecorder) ReadMessage(ctx, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockKafkaService)(nil).ReadMessage), ctx, topic)
}

// SendMessage mocks base method.
func (m *MockKafkaService) SendMessage(ctx context.Context, host, topic string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, host, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockKafkaServiceMockRecorder) SendMessage(ctx, host, topic, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockKafkaService)(nil).SendMessage), ctx, host, topic, payload)
}
