// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/private_data/private_data_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/GophKeeper/internal/service/private_data/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockPrivateDataService is a mock of PrivateDataService interface.
type MockPrivateDataService struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataServiceMockRecorder
}

// MockPrivateDataServiceMockRecorder is the mock recorder for MockPrivateDataService.
type MockPrivateDataServiceMockRecorder struct {
	mock *MockPrivateDataService
}

// NewMockPrivateDataService creates a new mock instance.
func NewMockPrivateDataService(ctrl *gomock.Controller) *MockPrivateDataService {
	mock := &MockPrivateDataService{ctrl: ctrl}
	mock.recorder = &MockPrivateDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataService) EXPECT() *MockPrivateDataServiceMockRecorder {
	return m.recorder
}

// SavePrivateData mocks base method.
func (m *MockPrivateDataService) SavePrivateData(ctx context.Context, req *dto.SavePrivateDataRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateData indicates an expected call of SavePrivateData.
func (mr *MockPrivateDataServiceMockRecorder) SavePrivateData(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateData", reflect.TypeOf((*MockPrivateDataService)(nil).SavePrivateData), ctx, req)
}
