// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/private_data_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/GophKeeper/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockPrivateDataRepository is a mock of PrivateDataRepository interface.
type MockPrivateDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataRepositoryMockRecorder
}

// MockPrivateDataRepositoryMockRecorder is the mock recorder for MockPrivateDataRepository.
type MockPrivateDataRepositoryMockRecorder struct {
	mock *MockPrivateDataRepository
}

// NewMockPrivateDataRepository creates a new mock instance.
func NewMockPrivateDataRepository(ctrl *gomock.Controller) *MockPrivateDataRepository {
	mock := &MockPrivateDataRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataRepository) EXPECT() *MockPrivateDataRepositoryMockRecorder {
	return m.recorder
}

// CreatePrivateData mocks base method.
func (m *MockPrivateDataRepository) CreatePrivateData(ctx context.Context, data *repository.PrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateData", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePrivateData indicates an expected call of CreatePrivateData.
func (mr *MockPrivateDataRepositoryMockRecorder) CreatePrivateData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateData", reflect.TypeOf((*MockPrivateDataRepository)(nil).CreatePrivateData), ctx, data)
}
