// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/sqlite/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlite "github.com/GophKeeper/internal/storage/sqlite"
	gomock "github.com/golang/mock/gomock"
)

// MockSqliteService is a mock of SqliteService interface.
type MockSqliteService struct {
	ctrl     *gomock.Controller
	recorder *MockSqliteServiceMockRecorder
}

// MockSqliteServiceMockRecorder is the mock recorder for MockSqliteService.
type MockSqliteServiceMockRecorder struct {
	mock *MockSqliteService
}

// NewMockSqliteService creates a new mock instance.
func NewMockSqliteService(ctrl *gomock.Controller) *MockSqliteService {
	mock := &MockSqliteService{ctrl: ctrl}
	mock.recorder = &MockSqliteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqliteService) EXPECT() *MockSqliteServiceMockRecorder {
	return m.recorder
}

// GetPrivateData mocks base method.
func (m *MockSqliteService) GetPrivateData(ctx context.Context, login string) ([]*sqlite.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateData", ctx, login)
	ret0, _ := ret[0].([]*sqlite.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateData indicates an expected call of GetPrivateData.
func (mr *MockSqliteServiceMockRecorder) GetPrivateData(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateData", reflect.TypeOf((*MockSqliteService)(nil).GetPrivateData), ctx, login)
}

// GetUserData mocks base method.
func (m *MockSqliteService) GetUserData(ctx context.Context, login string) (*sqlite.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", ctx, login)
	ret0, _ := ret[0].(*sqlite.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockSqliteServiceMockRecorder) GetUserData(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockSqliteService)(nil).GetUserData), ctx, login)
}

// SavePrivateData mocks base method.
func (m *MockSqliteService) SavePrivateData(ctx context.Context, pd *sqlite.PrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateData", ctx, pd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateData indicates an expected call of SavePrivateData.
func (mr *MockSqliteServiceMockRecorder) SavePrivateData(ctx, pd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateData", reflect.TypeOf((*MockSqliteService)(nil).SavePrivateData), ctx, pd)
}

// SaveUserData mocks base method.
func (m *MockSqliteService) SaveUserData(ctx context.Context, ud *sqlite.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserData", ctx, ud)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserData indicates an expected call of SaveUserData.
func (mr *MockSqliteServiceMockRecorder) SaveUserData(ctx, ud interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserData", reflect.TypeOf((*MockSqliteService)(nil).SaveUserData), ctx, ud)
}
