// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/gophkeeper.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateDataType int32

const (
	PrivateDataType_UNKNOWN PrivateDataType = 0
	PrivateDataType_TEXT    PrivateDataType = 1
	PrivateDataType_FILE    PrivateDataType = 2
	PrivateDataType_AUTH    PrivateDataType = 3
	PrivateDataType_BANK    PrivateDataType = 4
)

// Enum value maps for PrivateDataType.
var (
	PrivateDataType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXT",
		2: "FILE",
		3: "AUTH",
		4: "BANK",
	}
	PrivateDataType_value = map[string]int32{
		"UNKNOWN": 0,
		"TEXT":    1,
		"FILE":    2,
		"AUTH":    3,
		"BANK":    4,
	}
)

func (x PrivateDataType) Enum() *PrivateDataType {
	p := new(PrivateDataType)
	*p = x
	return p
}

func (x PrivateDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivateDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (PrivateDataType) Type() protoreflect.EnumType {
	return &file_api_gophkeeper_proto_enumTypes[0]
}

func (x PrivateDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivateDataType.Descriptor instead.
func (PrivateDataType) EnumDescriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type AuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *AuthUserResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type SavePrivateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type          PrivateDataType        `protobuf:"varint,2,opt,name=type,proto3,enum=shortener.PrivateDataType" json:"type,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Login         string                 `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePrivateDataRequest) Reset() {
	*x = SavePrivateDataRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePrivateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePrivateDataRequest) ProtoMessage() {}

func (x *SavePrivateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePrivateDataRequest.ProtoReflect.Descriptor instead.
func (*SavePrivateDataRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *SavePrivateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SavePrivateDataRequest) GetType() PrivateDataType {
	if x != nil {
		return x.Type
	}
	return PrivateDataType_UNKNOWN
}

func (x *SavePrivateDataRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SavePrivateDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type SavePrivateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePrivateDataResponse) Reset() {
	*x = SavePrivateDataResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePrivateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePrivateDataResponse) ProtoMessage() {}

func (x *SavePrivateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePrivateDataResponse.ProtoReflect.Descriptor instead.
func (*SavePrivateDataResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{5}
}

var File_api_gophkeeper_proto protoreflect.FileDescriptor

const file_api_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x14api/gophkeeper.proto\x12\tshortener\"G\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x16\n" +
	"\x14RegisterUserResponse\"C\n" +
	"\x0fAuthUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\x10AuthUserResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"\x88\x01\n" +
	"\x16SavePrivateDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.shortener.PrivateDataTypeR\x04type\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\"\x19\n" +
	"\x17SavePrivateDataResponse*F\n" +
	"\x0fPrivateDataType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04FILE\x10\x02\x12\b\n" +
	"\x04AUTH\x10\x03\x12\b\n" +
	"\x04BANK\x10\x042\xfc\x01\n" +
	"\n" +
	"GophKeeper\x12O\n" +
	"\fRegisterUser\x12\x1e.shortener.RegisterUserRequest\x1a\x1f.shortener.RegisterUserResponse\x12C\n" +
	"\bAuthUser\x12\x1a.shortener.AuthUserRequest\x1a\x1b.shortener.AuthUserResponse\x12X\n" +
	"\x0fSavePrivateData\x12!.shortener.SavePrivateDataRequest\x1a\".shortener.SavePrivateDataResponseB\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_api_gophkeeper_proto_rawDescOnce sync.Once
	file_api_gophkeeper_proto_rawDescData []byte
)

func file_api_gophkeeper_proto_rawDescGZIP() []byte {
	file_api_gophkeeper_proto_rawDescOnce.Do(func() {
		file_api_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gophkeeper_proto_rawDesc), len(file_api_gophkeeper_proto_rawDesc)))
	})
	return file_api_gophkeeper_proto_rawDescData
}

var file_api_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_gophkeeper_proto_goTypes = []any{
	(PrivateDataType)(0),            // 0: shortener.PrivateDataType
	(*RegisterUserRequest)(nil),     // 1: shortener.RegisterUserRequest
	(*RegisterUserResponse)(nil),    // 2: shortener.RegisterUserResponse
	(*AuthUserRequest)(nil),         // 3: shortener.AuthUserRequest
	(*AuthUserResponse)(nil),        // 4: shortener.AuthUserResponse
	(*SavePrivateDataRequest)(nil),  // 5: shortener.SavePrivateDataRequest
	(*SavePrivateDataResponse)(nil), // 6: shortener.SavePrivateDataResponse
}
var file_api_gophkeeper_proto_depIdxs = []int32{
	0, // 0: shortener.SavePrivateDataRequest.type:type_name -> shortener.PrivateDataType
	1, // 1: shortener.GophKeeper.RegisterUser:input_type -> shortener.RegisterUserRequest
	3, // 2: shortener.GophKeeper.AuthUser:input_type -> shortener.AuthUserRequest
	5, // 3: shortener.GophKeeper.SavePrivateData:input_type -> shortener.SavePrivateDataRequest
	2, // 4: shortener.GophKeeper.RegisterUser:output_type -> shortener.RegisterUserResponse
	4, // 5: shortener.GophKeeper.AuthUser:output_type -> shortener.AuthUserResponse
	6, // 6: shortener.GophKeeper.SavePrivateData:output_type -> shortener.SavePrivateDataResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gophkeeper_proto_init() }
func file_api_gophkeeper_proto_init() {
	if File_api_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gophkeeper_proto_rawDesc), len(file_api_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gophkeeper_proto_goTypes,
		DependencyIndexes: file_api_gophkeeper_proto_depIdxs,
		EnumInfos:         file_api_gophkeeper_proto_enumTypes,
		MessageInfos:      file_api_gophkeeper_proto_msgTypes,
	}.Build()
	File_api_gophkeeper_proto = out.File
	file_api_gophkeeper_proto_goTypes = nil
	file_api_gophkeeper_proto_depIdxs = nil
}
