// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/kafka.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateDataSaved_PrivateDataType int32

const (
	PrivateDataSaved_UNKNOWN_TYPE PrivateDataSaved_PrivateDataType = 0
	PrivateDataSaved_TEXT_TYPE    PrivateDataSaved_PrivateDataType = 1
	PrivateDataSaved_FILE_TYPE    PrivateDataSaved_PrivateDataType = 2
	PrivateDataSaved_AUTH_TYPE    PrivateDataSaved_PrivateDataType = 3
	PrivateDataSaved_BANK_TYPE    PrivateDataSaved_PrivateDataType = 4
)

// Enum value maps for PrivateDataSaved_PrivateDataType.
var (
	PrivateDataSaved_PrivateDataType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "TEXT_TYPE",
		2: "FILE_TYPE",
		3: "AUTH_TYPE",
		4: "BANK_TYPE",
	}
	PrivateDataSaved_PrivateDataType_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"TEXT_TYPE":    1,
		"FILE_TYPE":    2,
		"AUTH_TYPE":    3,
		"BANK_TYPE":    4,
	}
)

func (x PrivateDataSaved_PrivateDataType) Enum() *PrivateDataSaved_PrivateDataType {
	p := new(PrivateDataSaved_PrivateDataType)
	*p = x
	return p
}

func (x PrivateDataSaved_PrivateDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivateDataSaved_PrivateDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kafka_proto_enumTypes[0].Descriptor()
}

func (PrivateDataSaved_PrivateDataType) Type() protoreflect.EnumType {
	return &file_api_kafka_proto_enumTypes[0]
}

func (x PrivateDataSaved_PrivateDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivateDataSaved_PrivateDataType.Descriptor instead.
func (PrivateDataSaved_PrivateDataType) EnumDescriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{0, 0}
}

type PrivateDataSaved struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          PrivateDataSaved_PrivateDataType `protobuf:"varint,2,opt,name=type,proto3,enum=shortener.PrivateDataSaved_PrivateDataType" json:"type,omitempty"`
	Data          []byte                           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp           `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp           `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Nonce         []byte                           `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Login         string                           `protobuf:"bytes,7,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateDataSaved) Reset() {
	*x = PrivateDataSaved{}
	mi := &file_api_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateDataSaved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateDataSaved) ProtoMessage() {}

func (x *PrivateDataSaved) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateDataSaved.ProtoReflect.Descriptor instead.
func (*PrivateDataSaved) Descriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateDataSaved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivateDataSaved) GetType() PrivateDataSaved_PrivateDataType {
	if x != nil {
		return x.Type
	}
	return PrivateDataSaved_UNKNOWN_TYPE
}

func (x *PrivateDataSaved) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PrivateDataSaved) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PrivateDataSaved) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PrivateDataSaved) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PrivateDataSaved) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_api_kafka_proto protoreflect.FileDescriptor

const file_api_kafka_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/kafka.proto\x12\tshortener\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x10PrivateDataSaved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.shortener.PrivateDataSaved.PrivateDataTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\x12\x14\n" +
	"\x05login\x18\a \x01(\tR\x05login\"_\n" +
	"\x0fPrivateDataType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\r\n" +
	"\tTEXT_TYPE\x10\x01\x12\r\n" +
	"\tFILE_TYPE\x10\x02\x12\r\n" +
	"\tAUTH_TYPE\x10\x03\x12\r\n" +
	"\tBANK_TYPE\x10\x04B\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_api_kafka_proto_rawDescOnce sync.Once
	file_api_kafka_proto_rawDescData []byte
)

func file_api_kafka_proto_rawDescGZIP() []byte {
	file_api_kafka_proto_rawDescOnce.Do(func() {
		file_api_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kafka_proto_rawDesc), len(file_api_kafka_proto_rawDesc)))
	})
	return file_api_kafka_proto_rawDescData
}

var file_api_kafka_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_kafka_proto_goTypes = []any{
	(PrivateDataSaved_PrivateDataType)(0), // 0: shortener.PrivateDataSaved.PrivateDataType
	(*PrivateDataSaved)(nil),              // 1: shortener.PrivateDataSaved
	(*timestamppb.Timestamp)(nil),         // 2: google.protobuf.Timestamp
}
var file_api_kafka_proto_depIdxs = []int32{
	0, // 0: shortener.PrivateDataSaved.type:type_name -> shortener.PrivateDataSaved.PrivateDataType
	2, // 1: shortener.PrivateDataSaved.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: shortener.PrivateDataSaved.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_kafka_proto_init() }
func file_api_kafka_proto_init() {
	if File_api_kafka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kafka_proto_rawDesc), len(file_api_kafka_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kafka_proto_goTypes,
		DependencyIndexes: file_api_kafka_proto_depIdxs,
		EnumInfos:         file_api_kafka_proto_enumTypes,
		MessageInfos:      file_api_kafka_proto_msgTypes,
	}.Build()
	File_api_kafka_proto = out.File
	file_api_kafka_proto_goTypes = nil
	file_api_kafka_proto_depIdxs = nil
}
